---

#########################################################
## Vault module for Vault                              ##
#########################################################
# secret engine name (vault_name): vault
# secret engine type: kv
# secret name: default '{{ ansible_fqdn | replace('.', '-') }}'

# Validate variables
- name: Validate required variables for action.
  ansible.builtin.assert:
    that: "item is defined"
    fail_msg: "Required variable '{{ item }}' has not been provided."
    quiet: true
  with_items:
    - vault_address
    - vault_token

# Register variable (_secret_engine_name)
- name: Register variable (secret_engine_name)...
  ansible.builtin.set_fact:
   _secret_engine_name: "{{ openbao_vars.secrets.secret_engine_name | default('openbao-vault') }}"

# Register variable (_secret_name)
- name: Register variable (secret_name)...
  ansible.builtin.set_fact:
    _secret_name: "{{ openbao_vars.secrets.secret_name | default( ansible_fqdn | replace('.', '-') ) }}"

#########################################################
## Secret Engine                                       ##
#########################################################

# Create secret_engine if it does not exist
- name: "Create Vault secret engine for {{ _secret_engine_name }}..."
  ansible.builtin.include_tasks:
    file: roles/openbao/tasks/secret_engine/secret_engine.yml
  vars:
    action: create_secret_engine
    secret_engine_name: "{{ _secret_engine_name }}"
    secret_engine_description: "{{ openbao_vars.secrets.secret_engine_description | default('Secrets for OpenBao Vault.') }}"
    secret_engine_type: "kv"

#########################################################
## Secrets                                             ##
#########################################################

# Declare variable _secret_keyvalue
# <secret>: '{{ <secret> | default('change_me') }}'
- name: Register variable (secret_keyvalue)...
  ansible.builtin.set_fact:
    _secret_keyvalue: |
      repository_url : {{ openbao_vars.container.repository_url | default('change_me') }}
      vault_address : {{ vault_address | default('change_me') }}

# Store usernames and passwords in OpenBao Vault.
- name: Store secrets and configuration data in Vault...
  ansible.builtin.include_tasks:
    file: roles/openbao/tasks/secrets/create_secret.yml
  vars:
    action: create_secret
    secret_engine_name: "{{ _secret_engine_name }}"
    secret_name: "{{ _secret_name }}"
    secret_keyvalue: "{{ _secret_keyvalue | from_yaml }}"
