---
#########################################################
## SSL certificate                                     ##
#########################################################

# Register variables
- name: Register variables...
  ansible.builtin.set_fact:
    ssl_subject: /C=US/ST=State/L=City/O=Organization/OU=Unit/CN={{ ansible_fqdn }}
    ssl_extensions: subjectAltName = DNS:{{ ansible_fqdn }},IP:{{ ansible_default_ipv4.address }}

# Ensure destination folder exists
- name: Ensure destination folder exists
  ansible.builtin.file:
    path: "{{ destination_folder }}"
    state: directory
    mode: "0750"

# Run command
- name: Create SSL certificate
  ansible.builtin.command:
    cmd: openssl req -new -newkey rsa:2048 -sha256 -days 3650 -nodes -x509 -extensions v3_ca -keyout {{ destination_folder }}/private.key -out {{ 
      destination_folder }}/public.crt -subj '{{ ssl_subject }}' -addext '{{ ssl_extensions }}'
  register: action_result
  args:
    creates: "{{ destination_folder }}/public.crt"

#########################################################
## Post-actions                                        ##
#########################################################
