---
#########################################################
## Set action                                          ##
#########################################################
# If action variable is not defined, gather status of the service
# If service not installed, set action to install. 
# If the service is not started, set action to start.

# Gather installed packages
- name: Gather installed packages...
  ansible.builtin.package_facts:
    manager: auto

# Podman is installed
- name: Detected Podman package...
  when: '"podman" in ansible_facts.packages'
  block:
    # List containers with containers.podman collection
    - name: Gather containers from podman...
      containers.podman.podman_container_info:
        name: "{{ openbao_vars.container.name | default('openbao') }}"
      register: podman_containers
      failed_when: false

    # Set action variable to start if container is not running
    - name: Set variable (action)...
      ansible.builtin.set_fact:
        action: start
      when:
        - podman_containers.containers is defined
        - podman_containers.containers | length > 0
        - podman_containers.containers[0].State.Status is defined
        - podman_containers.containers[0].State.Status != 'running'

    # Set action variable to install if container is not installed
    - name: Set variable (action)...
      ansible.builtin.set_fact:
        action: install
      when: podman_containers.containers is not defined or (podman_containers.containers | length) == 0
